import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { BadgeCheck, Check, PackageCheck, ShieldCheck, Star, Store, Truck } from "lucide-react";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { ProductCard } from "@/components/product-card";
import { SectionHeading } from "@/components/ui/section-heading";
import { ProductActions } from "@/features/catalog/product-actions";
import { ProductGallery } from "@/features/catalog/product-gallery";
import { MobileProductPurchase } from "@/features/catalog/mobile-product-purchase";
import { RecentlyViewed } from "@/features/catalog/recently-viewed";
import { getProduct, products, relatedProducts } from "@/lib/catalog";
import { discountPercent, formatPrice } from "@/utils/format";
import { siteConfig } from "@/config/site";

export function generateStaticParams() { return products.map((product) => ({ slug: product.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const product = getProduct(slug); if (!product) return {}; return { title: product.name, description: product.shortDescription, alternates: { canonical: `/product/${slug}` }, openGraph: { type: "website", title: product.name, description: product.shortDescription, images: [product.image] } }; }

export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const product = getProduct(slug);
  if (!product) notFound();
  const price = product.salePrice ?? product.price;
  const discount = discountPercent(product.price, product.salePrice);
  const productJsonLd = { "@context": "https://schema.org", "@type": "Product", name: product.name, image: product.gallery.map((image) => `${siteConfig.url}${image}`), description: product.shortDescription, sku: product.sku, brand: { "@type": "Brand", name: product.brand }, aggregateRating: { "@type": "AggregateRating", ratingValue: product.rating, reviewCount: product.reviewCount }, offers: { "@type": "Offer", url: `${siteConfig.url}/product/${product.slug}`, priceCurrency: "IRR", price: price * 10, availability: product.stock ? "https://schema.org/InStock" : "https://schema.org/OutOfStock", itemCondition: "https://schema.org/NewCondition" } };
  const breadcrumbJsonLd = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "خانه", item: siteConfig.url }, { "@type": "ListItem", position: 2, name: product.category, item: `${siteConfig.url}/shop?category=${product.categorySlug}` }, { "@type": "ListItem", position: 3, name: product.name }] };
  return <><Breadcrumbs items={[{ label: "فروشگاه", href: "/shop" }, { label: product.category, href: `/shop?category=${product.categorySlug}` }, { label: product.name }]} /><div className="container-shell pb-32 lg:pb-20"><div className="grid gap-10 lg:grid-cols-2 lg:gap-14"><ProductGallery images={product.gallery} alt={`تصویر ${product.name}`} /><section><p className="text-sm font-black text-brand">{product.brand}</p><h1 className="mt-2 text-3xl font-black leading-tight md:text-4xl">{product.name}</h1><div className="mt-4 flex flex-wrap items-center gap-3 text-sm"><span className="inline-flex items-center gap-1 font-bold"><Star size={17} fill="#b78c62" strokeWidth={0} /> {new Intl.NumberFormat("fa-IR", {maximumFractionDigits:1}).format(product.rating)}</span><a href="#reviews" className="text-muted underline underline-offset-4">{new Intl.NumberFormat("fa-IR").format(product.reviewCount)} دیدگاه</a><span className="text-muted">کد کالا: <b dir="ltr">{product.sku}</b></span></div><p className="mt-6 leading-8 text-muted">{product.shortDescription}</p><div className="mt-6 flex items-center gap-3"><b className="price-ltr text-2xl">{formatPrice(price)}</b>{product.salePrice && <><del className="price-ltr text-sm text-muted">{formatPrice(product.price)}</del><span className="rounded-full bg-brand px-2.5 py-1 text-xs font-black text-white">٪{new Intl.NumberFormat("fa-IR").format(discount)}</span></>}</div><p className={`mt-4 inline-flex items-center gap-2 text-sm font-bold ${product.stock > 0 ? "text-sage" : "text-red-700"}`}><span className={`h-2 w-2 rounded-full ${product.stock > 0 ? "bg-sage" : "bg-red-700"}`} />{product.stock > 0 ? `موجود در انبار — ${new Intl.NumberFormat("fa-IR").format(product.stock)} عدد` : "در حال حاضر ناموجود"}</p><div className="mt-6"><p className="mb-3 text-sm font-black">مناسب برای</p><div className="flex flex-wrap gap-2">{product.skinTypes.map((type) => <span key={type} className="rounded-full bg-ivory px-3 py-2 text-xs font-bold">پوست {type}</span>)}</div></div><ProductActions product={product} /><div className="mt-5 grid grid-cols-2 gap-3 border-t border-black/10 pt-5 text-xs font-bold sm:grid-cols-3"><span className="inline-flex items-center gap-2"><ShieldCheck className="text-brand" size={19} /> ضمانت اصالت</span><span className="inline-flex items-center gap-2"><Truck className="text-brand" size={19} /> ارسال امن</span><span className="inline-flex items-center gap-2"><PackageCheck className="text-brand" size={19} /> پلمب سلامت</span></div><div className="mt-5 rounded-2xl border border-black/8 bg-ivory/75 p-4 text-sm"><div className="flex items-center gap-2 font-black"><Store size={18} className="text-brand" /> فروشنده: ماه‌ورا</div><div className="mt-2 grid gap-2 text-xs leading-6 text-muted sm:grid-cols-2"><p>تأمین و کنترل کیفیت پیش از ارسال</p><p>پرداخت فقط در مرحلهٔ نهایی و از مسیر امن</p></div></div></section></div>
    <div className="mt-16 grid gap-8 lg:grid-cols-[1fr_20rem]"><section><h2 className="section-title font-black">جزئیات محصول</h2><p className="mt-5 leading-9 text-muted">{product.description}</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{product.features.map((feature) => <p key={feature} className="surface-card flex items-center gap-3 p-4 text-sm font-bold"><Check className="text-sage" size={18} />{feature}</p>)}</div><div className="mt-9 divide-y divide-black/10 border-y border-black/10">{[["ترکیبات",product.ingredients],["روش استفاده",product.usage],["هشدارها",product.warnings],["ارسال و تحویل","زمان آماده‌سازی معمولاً ۱ تا ۲ روز کاری است. وضعیت ارسال از حساب کاربری قابل پیگیری خواهد بود."],["شرایط بازگشت","کالاهای آرایشی و بهداشتی فقط در صورت باز نشدن پلمب و مطابق شرایط بازگشت قابل مرجوعی هستند."]].map(([title,content]) => <details key={title} className="group py-5"><summary className="cursor-pointer list-none font-black">{title}<span className="float-left text-brand group-open:rotate-45">＋</span></summary><p className="pt-4 text-sm leading-8 text-muted">{content}</p></details>)}</div></section><aside className="surface-card h-fit bg-ivory p-6"><BadgeCheck className="text-brand" size={30} /><h2 className="mt-4 text-lg font-black">انتخاب مطمئن‌تر</h2><p className="mt-2 text-sm leading-7 text-muted">اطلاعات محصول از برچسب و منابع برند گردآوری می‌شود. ترکیبات ممکن است تغییر کنند؛ همیشه بسته‌بندی نهایی را بررسی کنید.</p></aside></div>
    <section id="reviews" className="mt-16 scroll-mt-28"><SectionHeading eyebrow="نظر خریداران" title={`${new Intl.NumberFormat("fa-IR").format(product.reviewCount)} تجربه ثبت‌شده`} /><div className="grid gap-5 md:grid-cols-[18rem_1fr]"><div className="surface-card p-6 text-center"><b className="text-5xl">{new Intl.NumberFormat("fa-IR", {maximumFractionDigits:1}).format(product.rating)}</b><div className="my-3 flex justify-center gap-1 text-gold">{Array.from({length:5}).map((_,i)=><Star key={i} size={19} fill="currentColor" />)}</div><p className="text-xs text-muted">بر اساس دیدگاه‌های تأییدشده و عمومی</p></div><div className="space-y-3">{["بافتش سبک بود و سریع جذب شد. بسته‌بندی هم کاملاً سالم به دستم رسید.","توضیحات سایت با تجربه محصول هم‌خوان بود و برای روتین روزانه انتخاب خوبی شد."].map((text,index)=><article className="surface-card p-5" key={text}><div className="flex items-center justify-between"><b>{index ? "آرزو م." : "بهاره ن."}</b><span className="text-xs font-bold text-sage">خرید تأییدشده</span></div><div className="mt-2 text-sm text-gold">★★★★★</div><p className="mt-3 text-sm leading-7 text-muted">{text}</p></article>)}</div></div></section>
    <section className="mt-16"><SectionHeading eyebrow="پیشنهاد برای شما" title="هم‌خانواده‌های این انتخاب" /><div className="product-grid">{relatedProducts(product).map((item) => <ProductCard key={item.id} product={item} />)}</div></section><RecentlyViewed current={product}/>
    </div><MobileProductPurchase product={product} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productJsonLd) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }} /></>;
}
