import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { blogPosts } from "@/lib/catalog";
import { siteConfig } from "@/config/site";
const content:Record<string,Array<{title:string;paragraphs:string[]}>>={
"simple-skin-routine":[{title:"سه پایه یک روتین پایدار",paragraphs:["پاک‌کننده ملایم، مرطوب‌کننده سازگار و ضدآفتاب سه بخش اصلی روتین روزانه‌اند. افزودن چند محصول هم‌زمان، تشخیص علت تحریک یا نتیجه هر محصول را دشوار می‌کند.","محصول جدید را یکی‌یکی اضافه کنید و به پوست زمان بدهید. تغییر مداوم روتین معمولاً از ثبات آن کم می‌کند."]},{title:"صبح و شب چه تفاوتی دارند؟",paragraphs:["صبح تمرکز بر رطوبت و محافظت در برابر نور است. شب فرصت پاک‌کردن آلودگی و آرایش و استفاده از مراقبت ساده فراهم می‌شود.","اگر پوست دچار سوزش، خارش مداوم یا ضایعه غیرعادی است، خوددرمانی را ادامه ندهید و از پزشک کمک بگیرید."]}],
"choose-sunscreen":[{title:"محافظت کافی و مصرف واقعی",paragraphs:["ضدآفتابی بهتر است که بتوانید مقدار کافی از آن را به‌صورت منظم استفاده و در صورت نیاز تمدید کنید. بافت مناسب سبک زندگی شما از ادعای تبلیغاتی مهم‌تر است.","SPF تنها معیار نیست؛ عبارت محافظت طیف‌گسترده و راهنمای روی بسته‌بندی را هم بررسی کنید."]},{title:"انتخاب بر اساس بافت",paragraphs:["پوست‌های چرب معمولاً با فلوئیدهای سبک راحت‌ترند و پوست خشک ممکن است بافت کرمی را ترجیح دهد. این یک قاعده قطعی نیست و تجربه شخصی اهمیت دارد."]}],
"makeup-skin-prep":[{title:"لایه‌های نازک، نتیجه طبیعی‌تر",paragraphs:["پوست تمیز و رطوبت‌رسانی متعادل، پایه خوبی برای آرایش است. میان محصولات کمی فاصله بدهید تا هر لایه بنشیند.","کرم‌پودر و کانسیلر را از مقدار کم شروع کنید و فقط جایی که نیاز است لایه بعدی اضافه کنید."]},{title:"وقتی بافت‌ها ناسازگارند",paragraphs:["اگر محصول گلوله می‌شود، ممکن است مقدار زیاد، فاصله کم میان لایه‌ها یا ناسازگاری بافت‌ها علت باشد. کم‌کردن مراحل معمولاً بهترین نقطه شروع است."]}]};
export function generateStaticParams(){return blogPosts.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const post=blogPosts.find(p=>p.slug===slug);if(!post)return{};return{title:post.title,description:post.excerpt,alternates:{canonical:`/blog/${slug}`},openGraph:{type:"article",title:post.title,description:post.excerpt,images:[post.image]}}}
export default async function Article({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const post=blogPosts.find(p=>p.slug===slug);if(!post)notFound();const sections=content[slug]??[];const jsonLd={"@context":"https://schema.org","@type":"Article",headline:post.title,description:post.excerpt,image:`${siteConfig.url}${post.image}`,datePublished:"2026-06-01",dateModified:"2026-06-01",author:{"@type":"Organization",name:"تحریریه ماه‌ورا"},publisher:{"@type":"Organization",name:siteConfig.name,logo:{"@type":"ImageObject",url:`${siteConfig.url}/brand/mahvara-mark.svg`}}};return <><Breadcrumbs items={[{label:"مجله",href:"/blog"},{label:post.title}]}/><article className="container-shell max-w-4xl pb-20"><header className="py-6 text-center"><p className="eyebrow">{post.category}</p><h1 className="mx-auto mt-3 max-w-3xl text-3xl font-black leading-tight md:text-5xl">{post.title}</h1><p className="mx-auto mt-4 max-w-2xl leading-8 text-muted">{post.excerpt}</p><p className="mt-4 text-xs text-muted">تحریریه ماه‌ورا · {post.date} · {post.readTime}</p></header><div className="relative my-8 aspect-[16/9] overflow-hidden rounded-[2rem]"><Image src={post.image} alt={`تصویر اصلی مقاله ${post.title}`} fill priority sizes="896px" className="object-cover"/></div><div className="prose-fa mx-auto max-w-3xl text-base leading-9"><p>این مطلب برای آگاهی عمومی نوشته شده و جایگزین تشخیص یا توصیه فردی پزشک نیست. در صورت التهاب پایدار یا بیماری پوستی، با متخصص مشورت کنید.</p>{sections.map(section=><section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map(p=><p key={p}>{p}</p>)}</section>)}</div></article><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/></>}
